php-nginx:
  image: richarvey/nginx-php-fpm:latest
  volumes:
    - ./conf/ssl:/opt/ssl
    - .:/var/www/html
  ports:
    - "80:80"
    - "443:443"
  environment:
    - PHP_MEM_LIMIT=512Mb
    - PHP_POST_MAX_SIZE=200M
    - PHP_UPLOAD_MAX_FILESIZE=200M
    - REDIS_PORT=6379
    - APP_NAME=KeepApp
  links:
    - mysql:mysql
    # - redis:redis
    # - beanstalkd:beanstalkd
    # - rabbitmq:rabbitmq

mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: secret

    #INSERT INTO tags_def (tag_id, tag_name) VALUES (17, 'test'), (NULL, 'abc') ON DUPLICATE KEY UPDATE tag_name =  VALUES(tag_name)

# redis:
#   image: redis:latest
#   ports:
#     - "6379:6379"

# elasticsearch:
#   image: elasticsearch:latest
#   ports:
#     - "9200:9200"
#     - "9300:9300"

# beanstalkd:
#   image: schickling/beanstalkd:latest
#   ports:
#     - "11300:11300"

# rabbitmq:
#   image: rabbitmq:3.6.9-management
#   ports:
#     - "15672:15672"
#     - "5672:5672"
